// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	     int n = Integer.parseInt(args[0]);
		 int countlow = 0;
		 int counthigh = 0;
		 for (int i = 0; i < n; i++) {
			 double randomNumber = Math.random();
			 if (randomNumber <= 0.5) {
				 countlow++;
			 } else {
				 counthigh++;
			 }
		 }
		 System.out.println("> 0.5: " + counthigh);
		 System.out.println("<= 0.5: " + countlow);
	}
}
